### ISSUE TITLE
Error validating Access Token

### ISSUE THREAD

**Issue by SgnAtWork** [codefog/contao-instagram#23] opened 2020-06-20 11:43 UTC
The module does not work permanently. After a certain time, nothing is displayed and the corresponding error message is in the log, see picture.
![83943221-ae878100-a7fa-11ea-9e8f-b6a5b1b9febd](https://user-images.githubusercontent.com/10742053/85200985-13af9c00-b2fc-11ea-99d7-55beae15d737.jpeg)

The installed version is 2.1.2. Do you have a solution for this?

**Comment by fritzmg** [comment] 2020-06-20 11:46
Duplicate of https://github.com/codefog/contao-instagram/issues/20

**Closed** 2020-06-20 11:50 UTC
